### ISSUE TITLE
Dismissing keyboard

### ISSUE THREAD

**Issue by nathjyo** [mbabicz/SwiftUI-ChatGPT-DALL-E-2#1]
dismissing the keyboard would be a good feature to add along with a way to save images and txt returned from openai

**Comment by mbabicz** [comment]
dismissing keyboard fixed ac27f8cd2574320b027ac5beea7073ee518c8120

**Comment by mbabicz** [comment]
Added options for sharing generated photos, including the ability to save them 79cdf225403bd98cd215d075744e65ec32cef6f1
