### ISSUE TITLE
Copy returned text

### ISSUE THREAD

**Issue by nathjyo** [mbabicz/SwiftUI-ChatGPT-DALL-E-2#2]
hi 

it would be great to create a way to copy the returned text from chat

also I was trying to find where to change the models used,

**Comment by mbabicz** [comment]
Added the ability to copy the returned text by long-pressing on the screen to open the copy menu (commit 00b7c10870). In the README file, you can find links to the OpenAI libraries that were used, which contain information about the available models. Additionally, it's worth noting that GPT 3.5 Turbo has also been implemented in commit 00b7c10870.

**Comment by nathjyo** [comment]
hi I noticed GPT3ViewModel is missing also you api key is visible in chatbotviewmodel

**Comment by mbabicz** [comment]
Yeah, thank you. The missing files have been added in the next commit. :) 
c4c3396554d24bedbed9d9bf89afe6b60289f50f
