### ISSUE TITLE
Dale 2 image save

### ISSUE THREAD

**Issue by nathjyo** [mbabicz/SwiftUI-ChatGPT-DALL-E-2#3]
Having fun with this repository I’ve downloaded to friends phones and there loving it beats paying for similar apps on the store, only issue at the moment is the ability to save Dalle-2 images to the camera roll at present can save to a folder, send share but can’t save to camera roll. Thanks 🙏

**Comment by mbabicz** [comment]
Thank you for your kind words, I'm glad to hear that you are enjoying the app.
Saving photos is located in the "share" option.
![git dalle2](https://user-images.githubusercontent.com/49866616/234521846-faa0603a-55db-45f6-97d2-7243b39b3680.PNG)
To make it easier, I have also added a button that directly saves photos to the camera roll. 8a47549d3102613ab97cddedc5e4d9557c4098a2
![greencar github](https://user-images.githubusercontent.com/49866616/234522764-da44a7b2-6b7e-4af5-8f4a-c26e739ac1b5.jpg)
